apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: temporal-worker-metrics

build:
  local:
    push: false
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: worker
      context: golang
      docker:
        dockerfile: Dockerfile.worker

deploy:
  helm:
    releases:
      - name: worker
        chartPath: helm/worker
        valuesFiles:
          - helm/worker/values.yaml
        setValueTemplates:
          image: "{{.IMAGE_REPO_worker}}"
          tag: "{{.IMAGE_TAG_worker}}"

profiles:
  - name: starters
    build:
      artifacts:
        - image: starter
          context: golang
          docker:
            dockerfile: Dockerfile.starter
    deploy:
      helm:
        releases:
          - name: starter
            chartPath: helm/starter
            valuesFiles:
              - helm/starter/values.yaml
            setValueTemplates:
              image: "{{.IMAGE_REPO_starter}}"
              tag: "{{.IMAGE_TAG_starter}}"

