apiVersion: batch/v1
kind: Job
metadata:
  name: starter-{{ now | unixEpoch }}
spec:
  completions: {{ .Values.completions }}
  parallelism: {{ .Values.parallelism }}
  backoffLimit: 50
  template:
    metadata:
      labels:
        app: starter
    spec:
      restartPolicy: OnFailure
      containers:
      - name: starter
        image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: TEMPORAL_ADDRESS
          value: "temporal:7233"
        - name: TEMPORAL_NAMESPACE
          value: "default"
