apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.replicas }}
  rollout:
    strategy: Progressive
    steps:
      - rampPercentage: 10
        pauseDuration: 5m
      - rampPercentage: 50
        pauseDuration: 10m
  sunset: {}
  workerOptions:
    connectionRef:
      name: local
    temporalNamespace: default
    {{- if .Values.buildID }}
    unsafeCustomBuildID: {{ .Values.buildID }}
    {{- end }}
  template:
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: worker
        image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - "-target-host=temporal:7233"
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    temporal.io/deployment-name: worker
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  type: ClusterIP
