apiVersion: v1
kind: Service
metadata:
  name: temporal-proxy-metrics
spec:
  selector:
    app.kubernetes.io/name: temporal-proxy
    app.kubernetes.io/instance: temporal-proxy
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
